# Generated by Django 2.2.2 on 2019-06-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfDimensions', models.IntegerField()),
                ('dimensionsString', models.CharField(max_length=1000)),
                ('entries', models.CharField(max_length=1000)),
            ],
        ),
    ]
