# Generated by Django 2.2.2 on 2019-07-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='outputImg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
