# Generated by Django 2.2.2 on 2019-07-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_matrix_outputimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrix',
            name='outputImg',
        ),
        migrations.AddField(
            model_name='matrix',
            name='output',
            field=models.ImageField(null=True, upload_to='outputImages/'),
        ),
    ]
