# Generated by Django 2.2.2 on 2019-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_matrix_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
