# Generated by Django 2.2.2 on 2019-07-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_matrix_dimensionsmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='output',
            field=models.ImageField(default='outputImages/rasql_1.png', upload_to='outputImages/'),
        ),
    ]
