# Generated by Django 2.2.2 on 2019-06-24 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProcessedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='processedImages/')),
                ('usr_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processedImages', to='blog.UserProfile')),
            ],
        ),
    ]
