# Generated by Django 2.2.2 on 2019-06-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_finalprocessedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalprocessedimage',
            name='image',
            field=models.FileField(upload_to='processedImages/'),
        ),
    ]
