# Generated by Django 2.2.2 on 2019-06-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190624_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalprocessedimage',
            name='image',
            field=models.ImageField(upload_to='processedImages/'),
        ),
    ]
